apiVersion: "kubeflow.org/v1alpha2"
kind: "PyTorchJob"
metadata:
  name: "pytorch-human-protein-atlas"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/optfit-kaggle/human-protein-atlas:latest
              securityContext:
                privileged: true
                capabilities:
                  add:
                    - SYS_ADMIN
              lifecycle:
                postStart:
                  exec:
                    command: ["gcsfuse", "-o", "nonempty", "human-protein-atlas-data", "/mnt/human-protein-atlas-data"]
                preStop:
                  exec:
                    command: ["fusermount", "-u", "/mnt/human-protein-atlas-data"]
              # todo: use a gpu after we figure out how to load in the data
              # resources:
              #   limits:
              #     nvidia.com/gpu: 1
