apiVersion: "kubeflow.org/v1beta1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-human-protein-atlas"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/optfit-kaggle/human-protein-atlas:latest
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/optfit-kaggle/human-protein-atlas:latest
