apiVersion: 0.3.0
environments:
  cloud:
    destination:
      namespace: default
      server: https://35.231.189.4
    k8sVersion: v1.10.9
    path: cloud
  default:
    destination:
      namespace: kubeflow
      server: https://35.237.156.164
    k8sVersion: v1.10.9
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/argo:
    name: argo
    registry: kubeflow
    version: ""
  kubeflow/core:
    name: core
    registry: kubeflow
    version: ""
  kubeflow/examples:
    name: examples
    registry: kubeflow
    version: ""
  kubeflow/katib:
    name: katib
    registry: kubeflow
    version: ""
  kubeflow/mpi-job:
    name: mpi-job
    registry: kubeflow
    version: ""
  kubeflow/pytorch-job:
    name: pytorch-job
    registry: kubeflow
    version: ""
  kubeflow/seldon:
    name: seldon
    registry: kubeflow
    version: ""
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: ""
name: ks_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: fs
    uri: /opt/kubeflow/kubeflow
version: 0.0.1
